<a href="https://colab.research.google.com/github/shahjamanbadhon/Data-Mining/blob/main/neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
input = [3.0,9.0,8.0,7.5]
weight = [0.2,-0.6,-0.2,6.0]
bias = 3.0


In [2]:
output = 0
for i in range(len(input)):
  output += input[i] * weight[i]
output += bias

print(output)

41.6


In [3]:
inputs = [1,2,3,2.5]
weight1 = [0.2,0.8,-0.5,1]
weight2 = [0.6,-0.91,0.26,-0.5]
weight3 = [-0.26,-0.27,0.17,0.87]
bias1 = 2
bias2 = 3
bias3 = 0.5

In [4]:
import numpy as np

weights = np.array([weight1, weight2, weight3])
biases = np.array([bias1, bias2, bias3])

outputs = np.dot(inputs, weights.T) + biases

print(outputs)

[4.8   1.31  2.385]


In [6]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

In [16]:
x = np.array([10,20,30])

In [17]:
sigmoid(x)


array([0.9999546, 1.       , 1.       ])

In [27]:
def relu(x):
  return np.maximum(0, x)

In [28]:
x = np.array([10,20,-30])

In [30]:
relu(x)

array([10, 20,  0])

In [70]:
def step_function(x, threshold=0):
  return np.where(x >= threshold, 1, 0)

In [50]:
x = 0.5
step_function(x)

1

In [72]:
input = np.array([[0,0],[0,1],[1,0],[1,1]])

labels = np.array([0,0,0,1])

w = np.array([0.5,-0.5])
bias = -0.7



In [73]:
output = np.dot(input, w) + bias

activated_output = sigmoid(output)

print(activated_output)

[0.33181223 0.23147522 0.450166   0.33181223]


In [74]:
step_function(output)

array([0, 0, 0, 0])

In [76]:
loss = np.mean((activated_output - labels) ** 2)
loss

np.float64(0.2032011148109052)

In [111]:
input = np.array([[0,0],[0,1],[1,0],[1,1]])
labels = np.array([0,0,0,1])
w1 = np.random.randn()
w2 = np.random.randn()
w3 = np.random.randn()
w4 = np.random.randn()
w5 = np.random.randn()
w6 = np.random.randn()
w7 = np.random.randn()
w8 = np.random.randn()
w9 = np.random.randn()
w10 = np.random.randn()
w11 = np.random.randn()
w12 = np.random.randn()
w13 = np.random.randn()
w14 = np.random.randn()
b1 = np.random.randn()
b2 = np.random.randn()
b3 = np.random.randn()
b4 = np.random.randn()
b5 = np.random.randn()
b6 = np.random.randn()



In [112]:

n1 = step_function(np.dot(input, [w1, w4]) + b1)
n2 = step_function(np.dot(input, [w2, w5]) + b2)
n3 = step_function(np.dot(input, [w3, w6]) + b3)

n4 = step_function(np.dot(np.array([n1, n2, n3]).T, [w7, w9, w10]) + b4)
n5 = step_function(np.dot(np.array([n1, n2, n3]).T, [w8, w11, w12]) + b5)

output = step_function(np.dot(np.array([n4, n5]).T, [w13, w14]) + b6)

print(output)

[0 0 0 0]


In [113]:
loss = np.mean((output - labels) ** 2)
loss

np.float64(0.25)